export { HomePage } from './HomePage'
export { OurStoryPage } from './OurStoryPage'
export { OurTeamPage } from './OurTeamPage'
export { AwardsRecognitionsPage } from './AwardsRecognitionsPage'
export { WinVinayaFoundationPage } from './WinVinayaFoundationPage'
export * from './common'
