export { HomePage } from './HomePage'
export { OurStoryPage } from './OurStoryPage'
export { OurTeamPage } from './OurTeamPage'
export { AwardsRecognitionsPage } from './AwardsRecognitionsPage'
export * from './common'
