export * from './TrainingHeroSection'
export * from './TrainingAreasSection'
export * from './TrainingProcessSection'
export * from './TrainingDifferentiatorsSection'
export * from './PastProgramsSection'
export * from './TrainingAudienceSection'
export * from './TrainingFormatSection'
export * from './TrainingCtaSection'
